# Configuration Site 1 (Port 80)
<VirtualHost *:80>
    DocumentRoot "/usr/local/apache2/htdocs/site1"
    <Directory "/usr/local/apache2/htdocs/site1">
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>
</VirtualHost>

# Configuration Site 2 (Port 8080)
<VirtualHost *:8080>
    DocumentRoot "/usr/local/apache2/htdocs/site2"
    <Directory "/usr/local/apache2/htdocs/site2">
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>
</VirtualHost>