version = 5.1.0
archive_dir = /etc/letsencrypt/archive/l1-10.ephec-ti.be
cert = /etc/letsencrypt/live/l1-10.ephec-ti.be/cert.pem
privkey = /etc/letsencrypt/live/l1-10.ephec-ti.be/privkey.pem
chain = /etc/letsencrypt/live/l1-10.ephec-ti.be/chain.pem
fullchain = /etc/letsencrypt/live/l1-10.ephec-ti.be/fullchain.pem
[renewalparams]
account = 84972d9da3ba5900fb85685a448497c4
pref_challs = dns-01,
authenticator = manual
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
