events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Configuration du format de log personnalisé (Étape 1.3)
    log_format log_per_virtualhost '[$host] $remote_addr [$time_local] $status '
                                   '"$request" $body_bytes_sent';

    # Utilisation du format personnalisé sur stdout pour Docker
    access_log /dev/stdout log_per_virtualhost;
    error_log /dev/stderr;

    # Virtual Host : WWW
    server {
        listen          80;
        server_name     www.l1-10.ephec-ti.be _ 91.134.137.239;
        index           index.html;
        root            /var/www/html/www;
	location ~* \.php$ {
		fastcgi_pass php-service:9000;
		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	}



	}

    # Virtual Host : BLOG
    server {
        listen          80;
        server_name     blog.l1-10.ephec-ti.be;
        index           index.html;
        root            /var/www/html/blog/;
    }
}
