limit_req_zone $binary_remote_addr zone=apilimit:10m rate=60r/m;

server {
    listen 80;
    server_name localhost;

    # --- MICROSERVICES API ---

    location /api/products {
        limit_req zone=apilimit;
        proxy_pass http://api-products:5000;
        proxy_set_header Host $host;
    }

    location /api/orders {
        limit_req zone=apilimit;
        proxy_pass http://api-users:5000;
        proxy_set_header Host $host;
    }

    location /api/misc {
        limit_req zone=apilimit;
        proxy_pass http://api-misc:5000;
        proxy_set_header Host $host;
    }

    # --- FRONT-END ---
  
    location / {
        proxy_pass http://front:80; 
        proxy_set_header Host $host;
    }
}
