options {
  directory "/var/cache/bind";
  version "not currently available";
  allow-query { any; };
  allow-query-cache { none; };
  recursion no;

  // Nouvelle ligne pour le support de l'IPv6
  listen-on-v6 { any; };
};

zone "l1-10.ephec-ti.be." {
  type master;
  file "/etc/bind/l1-10.ephec-ti.be.zone";
  allow-transfer { none; };

  // Activation de DNSSEC
  inline-signing yes;
  dnssec-policy default;
};
