version: '3.8'

services:
  exam_mail:
    image: mailserver/docker-mailserver:latest
    container_name: exam_mail
    hostname: mail
    domainname: ephec-ti.be
    ports:
      - "25:25"
      - "143:143"
    volumes:
      - ./dossier_mails:/var/mail
    environment:
      - ENABLE_SPAMASSASSIN=1
